# Generated by Django 5.0.6 on 2024-06-11 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_course_created_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
